'use client'

import Link from 'next/link'
import { ArrowUpRight, Check, Github, Linkedin, Mail, Moon, Sun, Download, ExternalLink } from 'lucide-react'
import { useTheme } from 'next-themes'
import { Button } from '@/components/ui/button'

const skills = {
  'AI & LLM': ['LLMOps', 'RAG', 'Prompt Engineering', 'LangChain', 'LlamaIndex', 'Semantic Kernel', 'Claude API', 'GPT-4o', 'MCP', 'Agentic AI', 'Vector DBs'],
  'Cloud Platforms': ['OCI', 'Azure', 'OCI Gen AI', 'Azure OpenAI', 'OCI AI Agents', 'OCI Functions', 'OCI Data Science', 'FSDR', 'Cloud Guard'],
  'Infrastructure & DevOps': ['Terraform', 'ARM Templates', 'GitHub Actions', 'Kubernetes', 'Python', 'Bash', 'PowerShell', 'Streamlit'],
  'Product & Strategy': ['Product Thinking', 'PRD Writing', 'Stakeholder Mgmt', 'Roadmapping', 'User Research', 'Agile', 'Technical Writing', 'Mentorship'],
  'Security & Networking': ['Azure Sentinel', 'OWASP/WAF', 'Palo Alto', 'Cisco ASA', 'BGP/OSPF', 'VPN/MPLS', 'Infoblox', 'DevSecOps'],
  'Tools & Workflows': ['Obsidian', 'Notion', 'Steampipe', 'Splunk', 'VS Code', 'Claude Code', 'Ollama', 'Hashnode'],
}
const projects = [
  ['Diagrams to Deployment', 'Python', 'AI reads architecture diagrams with OCI Gen AI Vision and generates Terraform. Won Oracle Innovation Month Award.', 'mukundmurali-mm/D2D'],
  ['Nibblify', 'JavaScript', 'Turns long YouTube videos into bite-sized daily episodes powered by Claude AI.', 'mukundmurali-mm/Nibblify'],
  ['OCI GenAI Chatbot', 'Python', 'Enterprise RAG chatbot using OCI Gen AI, vector embeddings, and LangChain.', 'mukundmurali-mm/oci-genai-chatbot'],
  ['Command Center', 'JavaScript', 'Locally-run personal wiki viewer for an Obsidian vault with AI-powered topic organization.', 'mukundmurali-mm/command-center'],
  ['Llama OCR on OCI', 'Python', 'Llama OCR with OCI Gen AI for structured text extraction from images.', 'mukundmurali-mm/llama-ocr-oci'],
  ['FSDR Plans Manager', 'Python', 'Streamlit app for OCI Full Stack Disaster Recovery management.', 'mukundmurali-mm/fsdr-plans-manager'],
  ['FSDR AI Agent', 'Python', 'AI agent automating OCI FSDR workflows for reliable disaster recovery.', 'mukundmurali-mm/fsdr-ai-agent'],
  ['Cloud Guard → Splunk', 'Python', 'OCI Functions integration exporting Cloud Guard alerts to Splunk via HEC.', 'mukundmurali-mm/cloudguard-splunk'],
  ['CD3 Streamlit', 'Python', 'Frontend for OCI infrastructure automation via Excel-driven Terraform generation.', 'mukundmurali-mm/cd3-streamlit'],
]
const experience = [
  ['Sep 2025 — Present', 'Technical Product Manager · Platform Engineering', 'LSEG', 'Leading platform product direction at the intersection of developer experience, cloud infrastructure, and AI.'],
  ['Jan 2022 — Sep 2025', 'Principal Cloud Architect', 'Oracle', 'Designed and shipped cloud and GenAI solutions for enterprise customers across industries.'],
  ['Feb 2021 — Jan 2022', 'Azure Customer Engineer', 'Microsoft', 'Partnered with customers to architect secure, scalable Azure platforms and modernize workloads.'],
  ['Jul 2018 — Jan 2021', 'Azure Network Support Engineer (L3)', 'Microsoft', 'Resolved complex networking challenges across enterprise Azure environments.'],
  ['Jun 2013 — Jul 2018', 'Senior Network Engineer', 'HCL Technologies', 'Built resilient network foundations for global enterprise systems.'],
]
const certifications = ['OCI Architect Professional', 'OCI GenAI Professional', 'OCI Data Science Professional', 'OCI Developer Professional', 'OCI DevOps Professional', 'OCI Networking Professional', 'Azure Solutions Architect Expert', 'OCI Security Associate', 'OCI AI Foundations Associate', 'Oracle Autonomous DB Cloud Professional']

function ThemeToggle() { const { theme, setTheme } = useTheme(); return <Button variant="ghost" size="icon" aria-label="Toggle theme" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="rounded-full">{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}</Button> }
function Header() { return <header className="sticky top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/" className="font-mono text-sm font-bold tracking-tight"><span className="text-primary">M</span>ukund <span className="text-muted-foreground">Murali</span></Link><nav className="hidden items-center gap-6 text-xs text-muted-foreground md:flex"><a href="#about" className="hover:text-foreground">About</a><a href="#work" className="hover:text-foreground">Work</a><a href="#experience" className="hover:text-foreground">Experience</a><Link href="/blog" className="hover:text-foreground">Writing</Link><a href="#contact" className="hover:text-foreground">Contact</a></nav><div className="flex items-center gap-2"><ThemeToggle /><a href="#contact" className="hidden rounded-full bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground md:block">Let&apos;s talk <ArrowUpRight className="ml-1 inline" size={13} /></a></div></div></header> }
function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="mb-10 max-w-2xl"><p className="mb-3 font-mono text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h2 className="text-3xl font-bold tracking-tight md:text-5xl">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-muted-foreground">{text}</p>}</div> }

export function Portfolio() { return <><Header /><main>
  <section className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-6xl items-center gap-12 px-5 py-20 md:grid-cols-[1.3fr_.7fr] md:py-28"><div><p className="mb-6 font-mono text-sm text-primary">Technical Product Manager / AI Builder</p><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] md:text-7xl">I build products for <span className="text-primary">complex</span> systems.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">13+ years building at the intersection of cloud infrastructure, Generative AI, and product thinking. I turn complex systems into elegant products.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="rounded-full px-6"><a href="#work">View projects <ArrowUpRight size={16} /></a></Button><Button asChild variant="outline" className="rounded-full px-6"><Link href="/blog">Read the blog <ArrowUpRight size={16} /></Link></Button></div></div><div className="md:justify-self-end"><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-border bg-border"><div className="bg-card p-5"><p className="font-mono text-3xl font-bold">13+</p><p className="mt-1 text-xs text-muted-foreground">Years experience</p></div><div className="bg-card p-5"><p className="font-mono text-3xl font-bold">20+</p><p className="mt-1 text-xs text-muted-foreground">Certifications</p></div><div className="bg-card p-5"><p className="font-mono text-3xl font-bold">15+</p><p className="mt-1 text-xs text-muted-foreground">Blog posts</p></div><div className="bg-card p-5"><p className="font-mono text-3xl font-bold">9+</p><p className="mt-1 text-xs text-muted-foreground">GitHub projects</p></div></div></div></section>
  <section id="about" className="border-y border-border bg-muted/20"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 md:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="01 / About" title="Product thinking, technical depth." /><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>Results-driven Technical Product Manager and Cloud Solutions Architect with 10+ years of experience translating ambitious ideas into shipped products.</p><p>I have shipped GenAI tools used by Fortune 500 clients and won Oracle&apos;s Innovation Month Award for Diagrams-to-Deployment, an AI tool that turns architecture into infrastructure.</p><p>My sweet spot is where product strategy meets implementation: LLMOps, RAG architectures, and Agentic AI workflows that make complex systems feel simple.</p><div className="grid grid-cols-2 gap-5 border-t border-border pt-6 text-sm"><div><p className="font-mono text-xs text-muted-foreground">Currently</p><p className="mt-1 text-foreground">Technical Product Manager, LSEG</p></div><div><p className="font-mono text-xs text-muted-foreground">Based in</p><p className="mt-1 text-foreground">Bengaluru, India</p></div><div><p className="font-mono text-xs text-muted-foreground">Education</p><p className="mt-1 text-foreground">B.E. Computer Science, Anna University</p></div><div><p className="font-mono text-xs text-muted-foreground">Email</p><a className="mt-1 block text-primary hover:underline" href="mailto:mukund.m.murali@gmail.com">mukund.m.murali@gmail.com</a></div></div></div></div></section>
  <section id="skills" className="mx-auto max-w-6xl px-5 py-24"><SectionHeading eyebrow="02 / Toolkit" title="The tools I use to make things real." text="A cross-functional toolkit spanning product discovery, cloud architecture, and applied AI." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Object.entries(skills).map(([name, items]) => <div key={name} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-semibold">{name}</h3><div className="mt-5 flex flex-wrap gap-2">{items.map(item => <span key={item} className="rounded-md bg-muted px-2.5 py-1.5 font-mono text-[11px] text-muted-foreground">{item}</span>)}</div></div>)}</div></section>
  <section id="work" className="border-y border-border bg-muted/20"><div className="mx-auto max-w-6xl px-5 py-24"><SectionHeading eyebrow="03 / Selected work" title="From diagrams to deployment." text="A selection of products and experiments built to remove friction from technical work." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map(([name, lang, desc, repo], i) => <article key={name} className="group flex min-h-64 flex-col justify-between rounded-2xl border border-border bg-card p-6 transition-shadow hover:shadow-xl hover:shadow-primary/5"><div><div className="mb-8 flex items-center justify-between"><span className="font-mono text-xs text-primary">0{i + 1}</span><span className="rounded-full border border-border px-2.5 py-1 font-mono text-[10px] text-muted-foreground">{lang}</span></div><h3 className="text-xl font-semibold">{name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p></div><a href={`https://github.com/${repo}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold text-foreground hover:text-primary">View on GitHub <ExternalLink size={14} /></a></article>)}</div></div></section>
  <section id="blog" className="mx-auto max-w-6xl px-5 py-24"><div className="flex items-end justify-between gap-5"><SectionHeading eyebrow="04 / Writing" title="Notes from the field." text="Ideas on AI, cloud infrastructure, and building products that work." /><Link href="/blog" className="mb-10 hidden items-center gap-2 text-sm font-semibold text-primary md:flex">View all writing <ArrowUpRight size={15} /></Link></div><div className="grid gap-4 md:grid-cols-3">{['Building reliable RAG systems in production','What MCP changes about AI product design','From architecture diagram to Terraform'].map((title, i) => <Link href="/blog" key={title} className="rounded-2xl border border-border p-6 transition-shadow hover:shadow-lg hover:shadow-primary/5"><p className="font-mono text-xs text-muted-foreground">0{i + 1} / AI & Cloud</p><h3 className="mt-16 text-lg font-semibold leading-7">{title}</h3><p className="mt-3 text-xs text-muted-foreground">6 min read · 2025</p></Link>)}</div></section>
  <section id="experience" className="border-y border-border bg-muted/20"><div className="mx-auto max-w-6xl px-5 py-24"><SectionHeading eyebrow="05 / Experience" title="A career in making systems better." /><div className="max-w-4xl">{experience.map(([date, role, company, desc]) => <div key={date} className="grid gap-3 border-t border-border py-7 md:grid-cols-[180px_1fr]"><p className="font-mono text-xs text-muted-foreground">{date}</p><div><h3 className="text-lg font-semibold">{role}</h3><p className="mt-1 text-sm font-medium text-primary">{company}</p><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{desc}</p></div></div>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-24"><SectionHeading eyebrow="06 / Credentials" title="Always staying curious." /><div className="grid gap-x-10 gap-y-4 md:grid-cols-2">{certifications.map(cert => <div key={cert} className="flex items-center gap-3 border-b border-border py-3 text-sm"><Check size={16} className="text-primary" />{cert}</div>)}</div></section>
  <section id="contact" className="border-t border-border bg-primary text-primary-foreground"><div className="mx-auto flex max-w-6xl flex-col gap-10 px-5 py-24 md:flex-row md:items-end md:justify-between"><div><p className="mb-4 font-mono text-xs uppercase tracking-[0.18em] opacity-70">07 / Contact</p><h2 className="max-w-2xl text-4xl font-bold tracking-tight md:text-6xl">Have a hard problem?<br />Let&apos;s build.</h2></div><div className="flex flex-col gap-3 text-sm"><a className="flex items-center gap-2 hover:underline" href="mailto:mukund.m.murali@gmail.com"><Mail size={16} /> mukund.m.murali@gmail.com</a><a className="flex items-center gap-2 hover:underline" href="https://linkedin.com/in/mukund-murali"><Linkedin size={16} /> LinkedIn</a><a className="flex items-center gap-2 hover:underline" href="https://github.com/mukundmurali-mm"><Github size={16} /> GitHub</a><button className="mt-4 inline-flex items-center gap-2 rounded-full border border-primary-foreground/30 px-4 py-2 text-xs font-semibold hover:bg-primary-foreground/10"><Download size={14} /> Download résumé</button></div></div></section>
</main><footer className="border-t border-border"><div className="mx-auto flex max-w-6xl justify-between px-5 py-6 text-xs text-muted-foreground"><span>© {new Date().getFullYear()} Mukund Murali</span><span className="font-mono">Built with curiosity.</span></div></footer></> }
